# Generated by Django 5.2.3 on 2025-06-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="anonymous", max_length=150, unique=True),
        ),
    ]
