# Generated by Django 5.2.3 on 2025-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
